kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: metrics
  name: statefulset-reader-patcher
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets", "statefulsets/status", "statefulsets/scale"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: scale-out
  namespace: metrics
subjects:
- kind: Group
  name: system:serviceaccounts:metrics
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: statefulset-reader-patcher
  apiGroup: rbac.authorization.k8s.io