apiVersion: v1
kind: Service
metadata:
  name: influxdbsvc
  labels:
    app: influxdbsvc
spec:
  clusterIP: None
  selector:
    app: {{ template "fullname" . }}
  ports:
  - name: api
    port: 8086
    targetPort: 8086
