## Query service image from ECR
image:
  repo: "gcr.io/ceres-dev-222017/metrics-query-service"
  tag: "latest"
  pullPolicy: Always

service:
  type: LoadBalancer

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 16Gi
    cpu: 8

config:
  target_port: 8080
  port: 80

containers:
  replicas: 1
  target_port: 8080
  liveness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 30
      timeout_seconds: 20
  readiness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 15
      timeout_seconds: 20

  influxdb_urls: "http://data-influxdb:8086"
  spring_profiles_active: production
  tenant_routing_service_url: "http://routing-tenant-routing-service:8080"
  rest_template_connection_request_timeout: 120000
  rest_template_connect_timeout: 120000
  rest_template_socket_timeout: 120000
  rest_template_connection_pooling_max: 20
