## Query service image from ECR
image:
  repo: "gcr.io/ceres-dev-222017/tenant-routing-service"
  tag: "latest"
  pullPolicy: Always

service:
  type: ClusterIP

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 2Gi
    cpu: 500m
  limits:
    memory: 16Gi
    cpu: 8000m

config:
  target_port: 8080
  port: 8080

containers:
  replicas: 3
  target_port: 8080
  liveness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 30
      timeout_seconds: 20
  readiness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 15
      timeout_seconds: 20

  redis_hostname: "lookup-redis"
  redis_port: 6379
  spring_profiles_active: production
  influxdb_metrics_url: "http://data-influxdb-0.influxdbsvc:8086"
  influxdb_scaler_url: http://influxdbscaler-influxdb-scaler:8080