## Ingestion service image from ECR
image:
  repo: "gcr.io/ceres-dev-222017/metrics-ingestion-service"
  tag: "latest"
  pullPolicy: Always

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 2Gi
    cpu: 1000m
  limits:
    memory: 16Gi
    cpu: 8000m

containers:
  replicas: 15
  target_port: 8080
  liveness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 30
      timeout_seconds: 20
  readiness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 15
      timeout_seconds: 20

  stackdriver_enabled: "true"
  stackdriver_batch_size: 150

  influxdb_metrics_url: "http://data-influxdb-0.influxdbsvc:8086"

  number_of_points_in_a_write_batch: 2000
  write_flush_duration_ms_limit: 100

  spring_profiles_active: production
  tenant_routing_service_url: "http://routing-tenant-routing-service:8080"
  rest_template_connection_request_timeout: 120000
  rest_template_connect_timeout: 120000
  rest_template_socket_timeout: 120000
  listener_container_idle_interval: 10000
  session_timeout_ms_config: 15000
  max_poll_records_config: 2000
  fetch_min_bytes_config: "8388608"
  fetch_max_wait_ms_config: 10
  max_partition_fetch_bytes_config: "8388608"
  rest_template_connection_pooling_max: 30
  secret_name: kafka-influxdb-java-secret
  secret_mount_path: "/etc/kafka-keys"
  kafka_servers: "kafka-01.dev.monplat.rackspace.net:9092;kafka-02.dev.monplat.rackspace.net:9092;kafka-03.dev.monplat.rackspace.net:9092;kafka-04.dev.monplat.rackspace.net:9092;kafka-05.dev.monplat.rackspace.net:9092"
  keystore_location: "/etc/kafka-keys/keystore-location"
  truststore_location: "/etc/kafka-keys/truststore-location"
  password_key: "store-password"
