## Ingestion service image from ECR
image:
  repo: "gcr.io/ceres-dev-222017/metrics-ingestion-service"
  tag: "latest"
  pullPolicy: Always

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 256Mi
    cpu: 0.1
  limits:
    memory: 16Gi
    cpu: 8

containers:
  replicas: 1
  target_port: 8080
  liveness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 30
      timeout_seconds: 20
  readiness_probe:
      path: "/actuator/health"
      port: 8080
      initial_delay_seconds: 15
      timeout_seconds: 20

  influxdb_url: "http://data-influxdb:8086"
  spring_profiles_active: production
  tenant_routing_service_url: "http://routing-tenant-routing-service:8080"
  rest_template_connection_request_timeout: 120000
  rest_template_connect_timeout: 120000
  rest_template_socket_timeout: 120000
  listener_container_idle_interval: 10000
  session_timeout_ms_config: 15000
  rest_template_connection_pooling_max: 20
  secret_name: kafka-influxdb-java-secret
  secret_mount_path: "/etc/kafka-keys"
  kafka_servers: "kafka-01.dev.monplat.rackspace.net:9092;kafka-02.dev.monplat.rackspace.net:9092;kafka-03.dev.monplat.rackspace.net:9092;kafka-04.dev.monplat.rackspace.net:9092;kafka-05.dev.monplat.rackspace.net:9092"
  keystore_location: "/etc/kafka-keys/keystore-location"
  truststore_location: "/etc/kafka-keys/truststore-location"
  password_key: "store-password"
