apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
spec:
  replicas: {{ .Values.containers.replicas }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: "{{ .Values.image.repo }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        ports:
        - containerPort: {{ .Values.containers.target_port }}

        livenessProbe:
          httpGet:
            path: {{ .Values.containers.liveness_probe.path }}
            port: {{ .Values.containers.liveness_probe.port }}
          initialDelaySeconds: {{ .Values.containers.liveness_probe.initial_delay_seconds }}
          timeoutSeconds: {{ .Values.containers.liveness_probe.timeout_seconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.containers.readiness_probe.path }}
            port: {{ .Values.containers.readiness_probe.port }}
          initialDelaySeconds: {{ .Values.containers.readiness_probe.initial_delay_seconds }}
          timeoutSeconds: {{ .Values.containers.readiness_probe.timeout_seconds }}

        env:
        - name: INFLUXDB_URL
          value: "{{ .Values.containers.influxdb_url }}"
        - name: SPRING_PROFILES_ACTIVE
          value: "{{ .Values.containers.spring_profiles_active }}"
